# permissions for end users to view mongoservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongoservice-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - mongoservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - mongoservices/status
  verbs:
  - get
