# permissions for end users to edit mongoservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongoservice-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - mongoservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - mongoservices/status
  verbs:
  - get
