# permissions for end users to edit myapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myapi-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - myapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - myapis/status
  verbs:
  - get
